### ISSUE TITLE
not that human readable yet

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/python-consistent-toml#7]
e.g.
In [17]: print data0.dumps()

[[user]]
id="despiegk" #official login name
firstname="Kristof"
lastname="De Spiegeleer"
mobile=["+32475405474","+971525609014"]
skype="despiegk"
git_aydo="despiegk"
git_github="despiegk"
email=["kristof@incubaid.com","kristof@greenitglobe.com"]
office=["dubai","lochr","cairo"]

I am sure some spacing would help
would be nice if you can look in how it was done with the jumpscale HRD

**Comment by amrhassan** [comment]
I'm sorry I don't quite understand your question. If this TOML snippet was constructed via contoml as so:
```python
>>> f = contoml.new()
>>> f.array('user').append({'id': 'despiegk', 'firstname': 'Kristof', 'lastname': "De Spiegeleer", "mobile": ["+32475405474","+971525609014"]})
>>> print(f.dumps())
```
It would serialize to this quite nicely formatted an spaced apart snippet:
```toml
[[user]]
lastname = "De Spiegeleer"
firstname = Kristof
id = despiegk
mobile = ["+32475405474", "+971525609014"]
```

If you wrote your TOML snippet manually however (which I presume is true since `contoml` doesn't support adding comments via its API) then it would not touch the formatting of any existing bit of the in loading/updating/serializing back. It was built under the assumption that the original files are written in a nice manner by humans and it doesn't mess up their markup or structure.

Are you looking for TOML-prettifying features in which you feed the module file and it consistently formats it using its own formatting rules?

**Comment by despiegk** [comment]
that was not the intention, intention is that the output is the same, no matter what was put in
comments should be kept but thats it

people are not consistent, we need some software to help us

otherwise we should make it an option

**Comment by amrhassan** [comment]
Okay, I'll plan adding the feature of optionally producing a consistent pretty-printed TOML structures from the inputs according to pre-specified formatting rules.

**Comment by amrhassan** [comment]
Feature request should be fulfilled by #8.
